/login:
    post:
        description: "Login as an admin"
        body:
            type: requestLogin
            example: !include examples/loginRequest.json
        responses:
            200:
                body:
                    type: responseAdmin
                    example: !include examples/adminLoginResponse.json
            400 401 404 500:
                !include ../errorResponse.raml
