/create:
    post:
        body:
            type: request.Channel
            example: !include examples/channelsCreateRequest.json
        responses:
            200:
                body:
                    type: response.Channel
                    example: !include examples/channelsCreateResponse.json
            500:
                !include ../errorResponse.raml