/create:
    post:
        body:
            type: request.Channel
            example: !include examples/channelsCreateRequest.json
        responses:
            200:
                body:
                    type: response.Channel
                    example: !include examples/channelsCreateResponse.json
            500:
                !include ../errorResponse.raml

/{id}/addUser/{userId}:
    patch:
        responses:
            200:
                !include ../successResponse.raml
            500:
                !include ../errorResponse.raml

/{id}/messages/{page?}:
    get:
        responses:
            200:
                body:
                    type: response.Messages
                    example: !include examples/messagesResponse.json
            500:
                !include ../errorResponse.raml