/:
    get:
        description: "Get all forbidden words for an organization"
        queryParameters:
            organizationId:
                description: "The organization for which to fetch the words"
                required: true
                type: integer
                example: 4
        responses:
            200:
                body:
                    type: responseForbiddenWord[]
                    example: !include examples/forbiddenWordsGetResponse.json
            400:
                !include ../errorResponse.raml

    post:
        description: "Add a forbidden word to an organization"
        headers:
            adminToken:
                description: The admin token
                type: string
                example: "dasfdsaf6546"
        body:
            type: requestForbiddenWord
            example: !include examples/forbiddenWordCreateRequest.json
        responses:
            200:
                body:
                    type: responseForbiddenWord
                    example: !include examples/forbiddenWordCreateResponse.json
            400:
                !include ../errorResponse.raml

/{id}:
    delete:
        description: "Deletes a forbidden word"
        headers:
            adminToken:
                description: The admin token
                type: string
                example: "dasfdsaf6546"
        responses:
            204:
            400:
                !include ../errorResponse.raml
