/{id}:
    get:
        description: "Get organization profile"
        responses:
            200:
                body:
                    type: responseOrganization
                    example: !include examples/organizationsGetByIdResponse.json
            500:
                !include ../errorResponse.raml

/:
    get:
        description: "Get organizations that belong to user"
        queryParameters:
            userId:
                description: "The user for which to fetch the organizations"
                required: true
                type: integer
                example: 4
        responses:
            200:
                body:
                    type: responseUserOrganizations
                    example: !include examples/organizationsGetForUserResponse.json
            500:
                !include ../errorResponse.raml

    post:
        description: "Create an organization"
        body:
            type: requestOrganization
            example: !include examples/organizationsCreateRequest.json
        responses:
            200:
                body:
                    type: responseOrganization
                    example: !include examples/organizationsCreateResponse.json
            500:
                !include ../errorResponse.raml

/{id}/invitations:
    post:
        description: "Invite an user to the organization"
        body:
            type: requestUserEmail
            example: !include examples/userEmailRequest.json
        responses:
            200:
                !include ../tokenResponse.raml
            500:
                !include ../errorResponse.raml

/{id}/users:
    post:
        description: "Add an user to the organization"
        body:
            !include ../tokenRequest.raml
        responses:
            200:
                !include ../successResponse.raml
            500:
                !include ../errorResponse.raml

/{id}/users/{userId}:
    delete:
        description: "Removes an user from the organization"
        responses:
            200:
                !include ../successResponse.raml
            500:
                !include ../errorResponse.raml