/{id}:
    get:
        responses:
            200:
                body:
                    type: response.OrganizationProfile
                    example: !include examples/organizationsGetByIdResponse.json
            500:
                !include ../errorResponse.raml

/create:
    post:
        body:
            type: request.Organization
            example: !include examples/organizationsCreateRequest.json
        responses:
            200:
                body:
                    type: response.Organization
                    example: !include examples/organizationsCreateResponse.json
            500:
                !include ../errorResponse.raml

/{id}/inviteUser:
    patch:
        body:
            type: request.UserEmail
            example: !include examples/userEmailRequest.json
        responses:
            200:
                !include ../tokenResponse.raml
            500:
                !include ../errorResponse.raml