/{id}:
    get:
        description: "Get organization profile"
        responses:
            200:
                body:
                    type: responseOrganization
                    example: !include examples/organizationsGetByIdResponse.json
            400:
                !include ../errorResponse.raml

    put:
        description: "Update an organization"
        body:
            type: requestOrganization
            example: !include examples/organizationsCreateRequest.json
        responses:
            204:
            400:
                !include ../errorResponse.raml

    delete:
        description: "Deletes organization"
        queryParameters:
            adminToken:
                description: The admin token
                required: true
                type: string
                example: "dasfdsaf6546"
        responses:
            204:
            400:
                !include ../errorResponse.raml

/:
    get:
        description: "Get organizations that belong to user"
        queryParameters:
            userToken:
                description: "The user for which to fetch the organizations. If not set returns all organizations."
                required: false
                type: string
                example: "abcdefghijk123"
        responses:
            200:
                body:
                    type: responseOrganizationWithRole[]
                    example: !include examples/organizationsGetForUserResponse.json
            400:
                !include ../errorResponse.raml

    post:
        description: "Create an organization"
        queryParameters:
            userToken:
                description: "The organization's creator"
                required: false
                type: string
                example: "abcdefghijk123"
            adminToken:
                description: "The admin"
                required: false
                type: string
                example: "afsdffghdsad"
        body:
            type: requestOrganization
            example: !include examples/organizationsCreateRequest.json
        responses:
            200:
                body:
                    type: responseOrganization
                    example: !include examples/organizationsCreateResponse.json
            400:
                !include ../errorResponse.raml

/{id}/invitations:
    post:
        description: "Invite users to the organization"
        body:
            type: requestUserEmails
            example: !include examples/userEmailRequest.json
        responses:
            200:
                body:
                    type: string[]
                    example: !include examples/organizationsInvitationsResponse.json 
            400:
                !include ../errorResponse.raml

/users:
    post:
        description: "Add an user to the organization"
        body:
            !include ../tokenRequest.raml
        responses:
            204:
            400:
                !include ../errorResponse.raml

/{id}/users/{userId}:
    put:
        description: "Update user's role in organization"
        queryParameters:
            adminToken:
                description: The admin token
                required: true
                type: string
                example: "dasfdsaf6546"
        body:
            type: requestUserRole
            example: !include examples/organizationsUserRoleRequest.json
        responses:
            204:
            400:
                !include ../errorResponse.raml

    delete:
        description: "Removes an user from the organization"
        responses:
            204:
            400:
                !include ../errorResponse.raml

/{id}/statistics:
    get:
        description: "Get statistics about the organization"
        responses:
            200:
                body:
                    type: responseOrganizationStatistics
                    example: !include examples/organizationsStatisticsResponse.json 
            400:
                !include ../errorResponse.raml