/:
    get:
        description: "Get messages from a channel"
        queryParameters:
            offset:
                description: "How many messages to skip (default: 0)"
                required: false
                type: integer
                example: 67
            channelId:
                description: "The channel for which to fetch the messages"
                required: true
                type: integer
                example: 4
            conversationId:
                description: "The conversation for which to fetch the messages"
                required: true
                type: integer
                example: 4
        responses:
            200:
                body:
                    type: responseMessage[]
                    example: !include examples/messagesListResponse.json
            500:
                !include ../errorResponse.raml
    post:
        queryParameters:
            userToken:
                description: "Message's sender"
                required: true
                type: string
                example: "abcdefghijk123"
        body:
            type: requestMessage
            example: !include examples/messageCreateRequest.json
        responses:
            200:
                !include ../successResponse.raml
            500:
                !include ../errorResponse.raml
