/{id}:
    get:
        description: "Get user profile"
        responses:
            200:
                body:
                    type: responseUser
                    example: !include examples/usersGetProfileResponse.json
            500:
                !include ../errorResponse.raml
    put:
        description: "Update user profile"
        body:
            type: requestUser
            example: !include examples/usersUpdateProfileRequest.json
        responses:
            200:
                !include ../successResponse.raml
            500:
                !include ../errorResponse.raml

/:
    get:
        description: "Get users that belong to an organization"
        queryParameters:
            organizationId:
                description: "The organization for which to fetch the users"
                required: true
                type: integer
                example: 18
        responses:
            200:
                body:
                    type: responseUserWithRole[]
                    example: !include examples/usersOrganizationsResponse.json
            500:
                !include ../errorResponse.raml
                
    post:
        description: "Register an user"
        body:
            type: requestUser
            example: !include examples/usersRegisterRequest.json
        responses:
            200:
                body:
                    type: responseUser
                    example: !include examples/usersRegisterResponse.json
            500:
                !include ../errorResponse.raml

/{id}/location:
    put:
        description: "Update user location"
        body:
            type: requestUserLocation
            example: !include examples/usersUpdateLocationRequest.json
        responses:
            200:
                !include ../successResponse.raml 
            500:
                !include ../errorResponse.raml