/profile:
    get:
        description: "Get user profile"
        queryParameters:
            userToken:
                description: "The user for which to fetch the profile"
                required: true
                type: string
                example: "abcdefghijk123"
        responses:
            200:
                body:
                    type: responseUser
                    example: !include examples/usersGetProfileResponse.json
            400:
                !include ../errorResponse.raml
    put:
        description: "Update user profile"
        queryParameters:
            userToken:
                description: "The user for which to update the profile"
                required: true
                type: string
                example: "abcdefghijk123"
        body:
            type: requestUserProfile
            example: !include examples/usersUpdateProfileRequest.json
        responses:
            204: 
            400:
                !include ../errorResponse.raml

/:
    get:
        description: "Get users that belong to an organization"
        queryParameters:
            organizationId:
                description: "The organization for which to fetch the users"
                required: true
                type: integer
                example: 18
        responses:
            200:
                body:
                    type: responseUserWithRole[]
                    example: !include examples/usersOrganizationsResponse.json
            400:
                !include ../errorResponse.raml
                
    post:
        description: "Register an user"
        body:
            type: requestUser
            example: !include examples/usersRegisterRequest.json
        responses:
            200:
                body:
                    type: responseUser
                    example: !include examples/usersRegisterResponse.json
            400:
                !include ../errorResponse.raml

/location:
    put:
        description: "Update user location"
        queryParameters:
            userToken:
                description: "The user for which to update the location"
                required: true
                type: string
                example: "abcdefghijk123"
        body:
            type: requestUserLocation
            example: !include examples/usersUpdateLocationRequest.json
        responses:
            204:
            400:
                !include ../errorResponse.raml

/invitations:
    get:
        description: "Get organizations that invited the user"
        queryParameters:
            userToken:
                description: "The user for which to fecth the invitations"
                required: true
                type: string
                example: "abcdefghijk123"
        responses:
            200:
                body:
                    type: responseUserInvitation[]
                    example: !include examples/userInvitationsResponse.json
            400:
                !include ../errorResponse.raml

/invitations/{invitationToken}:
    delete:
        description: "Deletes invitation to organization"
        responses:
            204:
            400:
                !include ../errorResponse.raml