/{id}:
    get:
        responses:
            200:
                body:
                    type: UserProfile
                    example: !include examples/usersGetProfileResponse.json
            500:
                !include errorResponse.raml

/register:
    post:
        body:
            type: UserRequest
            example: !include examples/usersRegisterRequest.json
        responses:
            200:
                body:
                    type: User
                    example: !include examples/usersRegisterResponse.json
            500:
                !include errorResponse.raml

/organizations/acceptInvitation/{token}:
    patch:
        responses:
            200:
                body:
                    type: object
                    properties:
                        accepted: boolean
                    example: 
                        accepted: true
            500:
                !include errorResponse.raml
