/{id}:
    get:
        responses:
            200:
                body:
                    type: User
                    example: !include examples/usersGetProfileResponse.json
            500:
                !include errorResponse.raml
    patch:
        body:
            type: UserRequest
            example: !include examples/usersUpdateProfileRequest.json
        responses:
            200:
                body:
                    !include successResponse.raml
            500:
                !include errorResponse.raml

/{id}/location:
    patch:
        body:
            type: UserUpdateLocation
            example: !include examples/usersUpdateLocationRequest.json
        responses:
            200:
                body:
                    !include successResponse.raml 
            500:
                !include errorResponse.raml

/register:
    post:
        body:
            type: UserRequest
            example: !include examples/usersRegisterRequest.json
        responses:
            200:
                body:
                    type: User
                    example: !include examples/usersRegisterResponse.json
            500:
                !include errorResponse.raml

/organizations/acceptInvitation/{token}:
    patch:
        responses:
            200:
                body:
                    !include successResponse.raml
            500:
                !include errorResponse.raml
