User:
  type: object
  properties:
    id: integer
    name: string
    surname: string
    email: string
    picture: string
    updatedAt: datetime
    createdAt: datetime
    latitude?: number
    longitude?: number

UserRole:
  type: object
  properties:
    role: string
    updatedAt: datetime
    createdAt: datetime

UserWithRole:
    type: User
    properties:
        UserOrganizations: UserRole

UserRequest:
  type: object
  properties:
    name: string
    surname: string
    email: string
    picture?: string

Organization:
    type: object
    properties:
        id: integer
        name: string
        picture: string
        latitude: number
        longitude: number
        description: string
        welcome: string
        updatedAt: datetime
        createdAt: datetime

OrganizationProfile:
    type: Organization
    properties:
        Users: UserWithRole[]
        Channels: Channel[]

OrganizationRequest:
    type: object
    properties:
        name: string
        picture: string
        latitude: number
        longitude: number
        description: string
        welcome: string
        creatorId: integer

Channel:
    type: object
    properties:
        id: integer
        name: string
        description: string
        welcome: string
        updatedAt: datetime
        createdAt: datetime

ChannelRequest:
    type: object
    properties:
        name: string
        description: string
        welcome: string
        creatorId: integer
        organizationId: integer

Error:
    type: object
    properties:
        error: string