#%RAML 1.0 Library

types:
    Success:
        type: object
        properties:
            success: boolean

    Error:
        type: object
        properties:
            error: string

    Token:
        type: object
        properties:
            token: string