#%RAML 1.0 Library

types:
    User:
        type: object
        properties:
            id: integer
            name: string
            surname: string
            email: string
            picture: string
            updatedAt: datetime
            createdAt: datetime
            latitude?: number
            longitude?: number

    UserRole:
        type: object
        properties:
            role: string
            updatedAt: datetime
            createdAt: datetime

    UserWithRole:
        type: User
        properties:
            userOrganizations: UserRole

    Organization:
        type: object
        properties:
            id: integer
            name: string
            picture: string
            latitude: number
            longitude: number
            description: string
            welcome: string
            updatedAt: datetime
            createdAt: datetime

    OrganizationWithRole:
        type: Organization
        properties:
            userOrganizations: UserRole

    UserOrganizations:
        type: object
        properties:
            organizations: OrganizationWithRole[]

    OrganizationUsers:
        type: object
        properties:
            users: UserWithRole[]

    Channel:
        type: object
        properties:
            id: integer
            name: string
            description: string
            visibility: string
            welcome: string
            updatedAt: datetime
            createdAt: datetime

    Channels:
        type: object
        properties:
            channels: Channel[]

    Message:
        type: object
        properties:
            id: integer
            type: string
            data: string
            createdAt: datetime
            updatedAt: datetime
            sender: User

    Messages:
        type: object
        properties:
            messages: Message[]

    ForbiddenWord:
        type: object
        properties:
            id: integer
            word: string

    ForbiddenWords:
        type: object
        properties:
            forbiddenWords: ForbiddenWord[]