#%RAML 1.0 Library

types:
    User:
        type: object
        properties:
            id: integer
            name: string
            surname: string
            email: string
            picture: string
            updatedAt: datetime
            createdAt: datetime
            latitude?: number
            longitude?: number

    UserRole:
        type: object
        properties:
            role: string
            updatedAt: datetime
            createdAt: datetime

    UserWithRole:
        type: User
        properties:
            userOrganizations: UserRole

    Organization:
        type: object
        properties:
            id: integer
            name: string
            picture: string
            latitude: number
            longitude: number
            description: string
            welcome: string
            updatedAt: datetime
            createdAt: datetime

    OrganizationData:
        type: Organization
        properties:
            users: UserWithRole[]

    OrganizationWithRole:
        type: Organization
        properties:
            userOrganizations: UserRole

    UserWithOrganizations:
        type: User
        properties:
            organizations: OrganizationWithRole[]

    Channel:
        type: object
        properties:
            id: integer
            name: string
            description: string
            welcome: string
            updatedAt: datetime
            createdAt: datetime

    ChannelWithUser:
        type: Channel
        properties:
            users: User[]

    OrganizationProfile:
        type: OrganizationData
        properties:
            userChannels: ChannelWithUser[]