commonSuccess:
    type: object
    properties:
        success: boolean

commonError:
    type: object
    properties:
        error: string

commonToken:
    type: object
    properties:
        token: string



requestUser:
    type: object
    properties:
        name: string
        token: string
        email: string
        picture: string
        username?: string

requestUserProfile:
    type: object
    properties:
        name: string
        username: string
        picture: string

requestUserLocation:
    type: object
    properties:
        latitude: number
        longitude: number

requestUserEmail:
    type: object
    properties:
        userEmail: string

requestUserId:
    type: object
    properties:
        userId: integer

requestOrganization:
    type: object
    properties:
        name: string
        picture: string
        latitude: number
        longitude: number
        description: string
        welcome: string

requestChannel:
    type: object
    properties:
        name: string
        description: string
        isPublic: boolean
        welcome: string
        organizationId: integer

requestMessage:
    type: object
    properties:
        type: string
        data: string
        senderId: integer
        channelId: integer

requestForbiddenWord:
    type: object
    properties:
        word: string
        organizationId: integer

requestToken:
    type: object
    properties:
        token: string

requestConversation:
    type: object
    properties:
        userId: integer
        organizationId: integer





responseUser:
    type: object
    properties:
        id: integer
        name: string
        email: string
        username: string
        picture: string
        updatedAt: datetime
        createdAt: datetime
        latitude?: number
        longitude?: number

responseUserRole:
    type: object
    properties:
        role: string
        updatedAt: datetime
        createdAt: datetime

responseUserWithRole:
    type: responseUser
    properties:
        userOrganizations: responseUserRole

responseOrganization:
    type: object
    properties:
        id: integer
        name: string
        picture: string
        latitude: number
        longitude: number
        description: string
        welcome: string
        updatedAt: datetime
        createdAt: datetime

responseOrganizationWithRole:
    type: responseOrganization
    properties:
        userOrganizations: responseUserRole

responseChannel:
    type: object
    properties:
        id: integer
        name: string
        description: string
        isPublic: boolean
        welcome: string
        updatedAt: datetime
        createdAt: datetime

responseMessage:
    type: object
    properties:
        id: integer
        type: string
        data: string
        createdAt: datetime
        updatedAt: datetime
        sender: responseUser

responseForbiddenWord:
    type: object
    properties:
        id: integer
        word: string

responseUserInvitation:
    type: object
    properties:
        token: string
        organization: string
        description: string
        invitedAt: datetime

responseConversation:
    type: object
    properties:
        id: integer
        users: responseUser[]