commonError:
    type: object
    properties:
        error: string

commonToken:
    type: object
    properties:
        token: string



requestUser:
    type: object
    properties:
        name: string
        token: string
        email: string
        picture: string
        username?: string

requestUserProfile:
    type: object
    properties:
        name: string
        username: string
        picture: string

requestUserLocation:
    type: object
    properties:
        latitude: number
        longitude: number

requestUserEmails:
    type: object
    properties:
        userEmails: string[]

requestUserId:
    type: object
    properties:
        userId: integer

requestOrganization:
    type: object
    properties:
        name: string
        picture: string
        latitude: number
        longitude: number
        description: string
        welcome: string

requestChannel:
    type: object
    properties:
        name: string
        description: string
        isPublic: boolean
        welcome: string
        organizationId: integer

requestMessage:
    type: object
    properties:
        type: string
        data: string
        channelId: integer
        conversationId: integer

requestBotMessage:
    type: object
    properties:
        message: string
        channelId: integer
        conversationId: integer
        bot: string

requestForbiddenWord:
    type: object
    properties:
        word: string
        organizationId: integer

requestToken:
    type: object
    properties:
        token: string

requestConversation:
    type: object
    properties:
        userId: integer
        organizationId: integer

requestLogin:
    type: object
    properties:
        username: string
        password: string

requestBot:
    type: object
    properties:
        name: string
        url: string
        organizationId: integer

requestUserRole:
    type: object
    properties:
        role: string





responseUser:
    type: object
    properties:
        id: integer
        name: string
        email: string
        username: string
        picture: string
        updatedAt: datetime
        createdAt: datetime
        latitude?: number
        longitude?: number

responseUserRole:
    type: object
    properties:
        role: string
        updatedAt: datetime
        createdAt: datetime

responseUserWithRole:
    type: responseUser
    properties:
        userOrganizations: responseUserRole

responseOrganization:
    type: object
    properties:
        id: integer
        name: string
        picture: string
        latitude: number
        longitude: number
        description: string
        welcome: string
        updatedAt: datetime
        createdAt: datetime

responseOrganizationWithRole:
    type: responseOrganization
    properties:
        userOrganizations: responseUserRole

responseChannel:
    type: object
    properties:
        id: integer
        name: string
        description: string
        isPublic: boolean
        welcome: string
        updatedAt: datetime
        createdAt: datetime

responseMessage:
    type: object
    properties:
        id: integer
        type: string
        data: string
        channelId?: integer
        conversationId?: integer
        createdAt: datetime
        updatedAt: datetime
        sender: responseUser

responseForbiddenWord:
    type: object
    properties:
        id: integer
        word: string
        createdAt: string
        updatedAt: string
        organizationId: number

responseUserInvitation:
    type: object
    properties:
        token: string
        organization: responseOrganization
        invitedAt: datetime

responseUserStatistics:
    type: object
    properties:
        organizations: string[]
        messagesSent: integer

responseConversation:
    type: object
    properties:
        id: integer
        users: responseUser[]

responseChannelStatistics:
    type: object
    properties:
        messageCount: integer

responseAdmin:
    type: object
    properties:
        id: integer
        username: string
        token: string
        createdAt: datetime
        updatedAt: datetime

responseBot:
    type: object
    properties:
        id: integer
        name: string
        url: string
        createdAt: datetime
        updatedAt: datetime

responseRolesCount:
    type: object
    properties:
        role: string
        count: integer

responseMessagesCount:
    type: object
    properties:
        type: string
        count: integer

responseOrganizationStatistics:
    type: object
    properties:
        usersCount: responseRolesCount[]
        messagesCount: responseMessagesCount[]
